version: '2'
services:
  wordpress:
    image: wordpress
    depends_on:
     - mysql
    ports:
     - "80:80"
    env_file: secrets.env
  mysql:
    image: mariadb
    env_file: secrets.env
  dump: &dump_restore
    build:
      context: .
      dockerfile: dump_restore.Dockerfile
    depends_on:
     - mysql
    env_file: secrets.env
    volumes:
     - .:/tmp
    entrypoint: 
     - /usr/local/bin/dump_restore
     - dump
    command:
     - wordpress
  restore:
    <<: *dump_restore
    entrypoint: 
     - /usr/local/bin/dump_restore
     - restore
    command: []

