version: '2'
services:
  wordpress:
    image: wordpress
    depends_on:
     - mysql
    ports:
     - "80:80"
    env_file: secrets.env
  mysql:
    image: mariadb
    env_file: secrets.env
  dump: &dump_restore
    image: mariadb
    depends_on:
     - mysql
    env_file: secrets.env
    volumes:
     - .:/tmp
    command: 
     - bash
     - -c
     - mysqldump --host mysql --password=$$MYSQL_ROOT_PASSWORD wordpress > /tmp/dump.sql
  restore:
    <<: *dump_restore
    command: 
     - bash
     - -c
     - mysql --host mysql --password=$$MYSQL_ROOT_PASSWORD --database=wordpress < /tmp/dump.sql


