version: '2'
services:
  wordpress:
    image: wordpress
    depends_on:
     - mysql
    ports:
     - "80:80"
    environment:
      WORDPRESS_DB_PASSWORD: example
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example


