version: '2'
networks:
  vhosts:
    external: 
      name: nginx_vhosts
services:
  nginx: &nginx
    image: nginx
    ports:
    - '80:80'
    networks:
    - vhosts
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ./web:/usr/share/nginx
    restart: always
  test:
    <<: *nginx
    command: nginx -t
  init:
    image: nginx
    volumes:
    - .:/tmp/
    command: bash -c 'rm -r /tmp/conf.d /tmp/web; cp -r /etc/nginx/conf.d /tmp/conf.d; cp -r /usr/share/nginx /tmp/web'
